[tool.poetry]
name = "delta"
version = "0.1.0"
description = ""
authors = ["emiliano bonilla <emilbon99@gmail.com>"]

[tool.mypy]
plugins = ["numpy.typing.mypy_plugin"]
ignore_missing_imports = true

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.1.2"
websockets = "^10.3"
pytest-asyncio = "^0.19.0"
freighter = { path = "../../freighter/py", develop = true }
numpy = "^1.23.1"
mypy = "^0.971"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
