[tool.poetry]
name = "arya-client"
version = "0.1.0"
description = "Arya Client Library"
keywords = ["Arya", "Arya Python Client"]
authors = ["emiliano bonilla <emilbon99@gmail.com>"]
repository = "https://github.com/arya-analytics/arya"
homepage = "https://aryaanalytics.com"
packages = [
    { include = "arya/**/*.py" }
]


[tool.poetry.dependencies]
python = "^3.10"
websockets = "^10.3"
numpy = "^1.23.1"
mypy = "^0.971"
arya-freighter = "^0.1.0"
pandas = "^1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"
pytest-cov = "^3.0.0"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["numpy.typing.mypy_plugin"]
ignore_missing_imports = true