name: go-lint
on:
  push:
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
        with:
          repository: 'arya-analytics/mono'
          ref: ${{ github.ref_name }}
          path: .
      - name: Run lint
        uses: golangci/golangci-lint-action@v3

