[tool.poetry]
name = "freighter"
version = "0.1.0"
description = ""
authors = ["emiliano bonilla <emilbon99@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.1.2"
websockets = "^10.3"
pytest-asyncio = "^0.19.0"
msgpack = "^1.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
