name: Deploy Documentation Site
on:
  push:
    paths:
      - "docs/site/**"
      - ".github/workflows/docs.deploy.yaml"
jobs:
  build:
    name: Build Documentation Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'x/ts/**'
              - 'x/meta/**'
              - 'pluto/**'
              - 'docs/site/**'
              - '.github/workflows/docs.deploy.yaml'

      - name: Set up pnpm
        if: steps.filter.outputs.changed == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set up Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm i

      - name: Build Documentation Site
        if: steps.filter.outputs.changed == 'true'
        run: pnpm build:docs

      - name: Upload Pages Artifact
        if: steps.filter.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/site/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
