name: "Pluto Chromatic"
on:
  push:
    paths:
      - 'pluto/**'
      - '.github/workflows/pluto.chromatic.yaml'
    branches:
      - main
  pull_request:
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        working-directory: pluto
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: pluto
          projectToken: ${{ secrets.PLUTO_CHROMATIC_PROJECT_TOKEN }}
