name: "Pluto Publish"
on:
  push:
    paths:
      - 'pluto/**'
      - '.github/workflows/pluto.publish.yaml'
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        working-directory: ./pluto
      - name: Package Lib
        run: yarn build
        working-directory: ./pluto
      - name: Authenticate With Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
        working-directory: ./pluto
      - name: Publish to Registry
        run: npm publish
        working-directory: ./pluto
