name: "Synnax Test"
on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - 'synnax/**'
      - '.github/workflows/synnax.test.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test
        run: go test -tags noui -v ./... --covermode=atomic --coverprofile=coverage.txt --ginkgo.label-filter="!integration && !performance"
        working-directory: ./synnax
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./synnax
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: synnax
