name: "X Test"
on:
  push:
    paths:
      - 'x/**'
      - '.github/workflows/x.test.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: go build -v ./...
      - name: Set Up Tests
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.0.0
          go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.0.0
          go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.0.0
          go install github.com/onsi/ginkgo/v2/ginkgo
        working-directory: ./x
      - name: Test
        run: ginkgo -r --covermode=atomic --coverprofile=coverage.txt -covermode=atomic
        working-directory: ./x
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./x