name: "X Test"
on:
  push:
    paths:
      - 'x/**'
      - '.github/workflows/x.test.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test
        run: go test -v --covermode=atomic --coverprofile=coverage.txt ./...
        working-directory: ./x
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./x